/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AInput: typeof import('ant-design-vue/es')['Input']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  }
}
